[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  REACT_APP_SITE_URL = "https://diligencefinance.netlify.app"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0"
    Content-Type = "application/javascript"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "application/javascript"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://*.supabase.co; frame-ancestors 'none'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 